// Generated by scripts/generate-og-home.mjs. Do not edit by hand.
// The filename carries a hash of the image bytes so a new card gets a new
// URL, which is the only thing that reliably beats a cached link preview.
export const OG_HOME = "/og/home-5987c58f51.png";
